//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEN341InstagramReplica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public string Comment1 { get; set; }
        public Nullable<System.DateTime> Date_Posted { get; set; }
        public int User_ID { get; set; }
        public string Username { get; set; }
        public int Post_ID { get; set; }
    
        public virtual UserPost UserPost { get; set; }
        public virtual User User { get; set; }
    }
}
